// import useState from react
import Head from 'next/head';

import Alert from '@mui/material/Alert'; // used for error messaging
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem'; // used for movie display
import ListItemText from '@mui/material/ListItemText'; // used for movie display

import { MOVIE_LIST } from '../utils/movies'; // used for movie display

export default function Home() {
  return (
    <div>
      {/* use Head component to control meta for the page */}
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{ textAlign: "center" }}>
            Movies
          </Typography>
          <form
            style={{ width: '100%' }}
          >
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{ width: '100%' }}
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{ width: '100%' }}
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                >Filter</Button>
              </Grid>
              {/* error message display */}
              <Grid item xs={10}></Grid>
            </Grid>
          </form>
          <List sx={{ width: '100%' }}>
            {/* render movies, if any */}
          </List>
        </Container>
      </main>
    </div>
  );
}
